### ISSUE TITLE
Powermock 和 robolectric冲突

### ISSUE THREAD

**Issue by AlexMahao** [simplezhli/AndroidUT#3]
请问一下有遇到过powermock和robolectric冲突的情况吗?

两个库一直用会遇到mock时，when逻辑直接执行了方法，而不是mock。

**Comment by simplezhli** [comment]
@AlexMahao 能具体说明吗？不知道是不是我之前文中提到的这个原因？

![)Q)YPEFY L7PUX`))53I8%L](https://user-images.githubusercontent.com/12456431/68571889-0a756b80-049f-11ea-875d-440290b0f5e8.png)

**Comment by AlexMahao** [comment]
自定义的Activity包含了一个私有方法的代码：

```java
   private synchronized void startNextActivity(boolean isClick) {
       
    }

```

我想`mock`该方法，当走到该方法时，不执行内部逻辑，同时验证该方法是否被调用且参数是否正确。

```java

Powermockito.doReturn(true).when(obj, "startNextActivity", true); // 大致代码是这样
```

但是该mock实际上做的不是mock操作，而是运行。也就是说上面的`mock`代码的操作是  调用并执行`startNextActivity(true)`。

**Comment by AlexMahao** [comment]
大致的意思是上面这样，具体代码没有保存。抱歉。

**Comment by simplezhli** [comment]
@AlexMahao 我按照你说的做了尝试，确实存在一些问题。不过我也不建议你这样测试，尽量将逻辑操作放到类似Presenter里面去测试，去mock Presenter，分离所需的Android环境。或者给测试方法加上`@VisibleForTesting`注解，改为pubilc方法。

**Comment by AlexMahao** [comment]
@simplezhli 嗯嗯，但是项目整体架构不是mvp，也不太好重构。最终是放弃了使用robolectric，仅仅使用Powermock来进行。
