### ISSUE TITLE
请问怎么查看覆盖率,jacoco 查看覆盖率html是空的

### ISSUE THREAD

**Issue by huangruiLearn** [simplezhli/AndroidUT#4]

**Comment by simplezhli** [comment]
@huangruiLearn 不好意思哈，之前更新忘记修改文件目录了。
jacoco.gradle文件中将：
`${buildDir}/intermediates/classes/debug`
修改为：
`"${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes`

**Comment by huangruiLearn** [comment]
![image](https://user-images.githubusercontent.com/30585790/72500723-2961f680-3870-11ea-9878-132f63d33620.png)  为什么只有dateutil有覆盖率 其他的都是0% @simplezhli

**Comment by simplezhli** [comment]
添加如下配置至jacoco.gradle：
```
tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
}
```

![image](https://user-images.githubusercontent.com/12456431/72503779-81502b80-3877-11ea-9de9-5b718fabf7b2.png)
