### ISSUE TITLE
您好，我按照您的项目配置jacoco覆盖率，但是只有report/androidTests文件夹下生成了报告，没有coverage目录，请问您知道是怎么回事吗？

### ISSUE THREAD

**Issue by gxs-gc** [simplezhli/AndroidUT#5]
![image](https://user-images.githubusercontent.com/12170093/124920734-3bb68e00-e02a-11eb-97c3-df2f2138c976.png)

**Comment by simplezhli** [comment]
有引入`apply from: 'jacoco.gradle'`吗？使用见这篇博客https://weilu.blog.csdn.net/article/details/79277483  ，配置用项目最新的就行。

**Comment by simplezhli** [comment]
@zhaolijunstar  `jacocoTestReport `任务跳过执行了。主要是executionData目录位置变更了，导致执行跳过。我已经修复了，可以查看提交代码。

**Comment by zhaolijunstar** [comment]
我把您那个jacoco拷贝到一个application module 运行生成覆盖率没问题，但是拷贝到一个library module 运行生成的覆盖率是0，生成的testDebugUnitTest.exec文件中只有一行，想问下，您知道是什么问题，要怎么解决吗，是不是路径问题呢，这个路径，我已经您改成 下面的通用路径，麻烦您看下是什么问题，谢谢，能不能加个问题交流下呢，我的微信是17607109290，谢谢，有偿咨询
def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes", //指定类文件夹
            includes: ["**/*.*"], //包含类的规则,这里我们生成所有类的测试报告
            excludes: ['**/R.class',
                       '**/R$*.class',
                       '**/BuildConfig.*',
                       '**/Manifest*.*']) //排除类的规则

**Comment by simplezhli** [comment]
@zhaolijunstar jacoco并不能很好的支持Android多module的情况，需要手动配置各个module的source，class，比较麻烦，而且不能单独看某个module的覆盖数据。建议你使用[Android-Root-Coverage-Plugin](https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin)插件。
