### ISSUE TITLE
拉最新项目下来运行测试，还是不会生成jacocoTestReport这个包。  只有testDebugUnitTest

### ISSUE THREAD

**Issue by xiaoyuhao1995** [simplezhli/AndroidUT#6]
也尝试了Issues中的方案，还是没有Jacoco的覆盖率报告

**Comment by simplezhli** [comment]
@xiaoyuhao1995 是否有执行`jacocoTestReport`任务？

**Comment by simplezhli** [comment]
最好能提供一下build信息。

**Comment by xiaoyuhao1995** [comment]
![1](https://user-images.githubusercontent.com/39255279/139033062-dbed950f-3ccf-4959-866f-069b653a9789.png)
![2](https://user-images.githubusercontent.com/39255279/139033069-372d175b-4d4e-4b20-84ff-dd50886172a2.png)
![3](https://user-images.githubusercontent.com/39255279/139033086-239b84ba-96ea-4399-ae2c-b2b1daa6ca75.png)
这是执行jacocoTestReport任务后的信息

**Comment by simplezhli** [comment]
单元测试执行失败了，先看一下什么原因。首先要保证测试都通过。
