### ISSUE TITLE
作者你好，仿照demo写Activity跳转测试 findViewById返回null 

### ISSUE THREAD

**Issue by excellenttank** [simplezhli/AndroidUT#7]
![image](https://user-images.githubusercontent.com/16424424/180186405-73198b67-3f66-4a68-be84-18b21d4900ea.png)

**Comment by simplezhli** [comment]
@excellenttank 这个view id是这个activity的吗？

**Comment by excellenttank** [comment]
> @excellenttank 这个view id是这个activity的吗？

是这个activity的，跟BaseActivity是基础model里面的有关系吗，因为这个Activity是继承BaseActivity的，

**Comment by simplezhli** [comment]
你试试用`ActivityScenario` 替代 `ActivityTestRule`获取view。具体使用可以参考代码里的`AssertJAndroidTest`示例。

**Comment by excellenttank** [comment]
> AssertJAndroidTest

![image](https://user-images.githubusercontent.com/16424424/182572616-6b61ac46-e894-49fd-831d-5475bd76bdfc.png)
不知道为何 launch后就被destroy了

**Comment by excellenttank** [comment]
> 你试试用`ActivityScenario` 替代 `ActivityTestRule`获取view。具体使用可以参考代码里的`AssertJAndroidTest`示例。
![image](https://user-images.githubusercontent.com/16424424/182573433-fc84448b-efef-4898-a52d-93710191e86f.png)

不知为何 launch之后就destroy了，网上也没搜到什么解决方法

**Comment by simplezhli** [comment]
不清楚这个activity有什么特别的地方，要不你换一个activity。或是写一个简单的activity试试是否正确。

**Comment by excellenttank** [comment]
> 不清楚这个activity有什么特别的地方，要不你换一个activity。或是写一个简单的activity试试是否正确。

应该时我老项目的问题，我写个新demo就没问题，我再找找原因
